# Jekyll
markdown: rdiscount
highlighter: "rouge"
permalink: /:title.html

# Conference info
conf:
  name: "Women Techmakers Aracaju"
  description: "Women Techmakers Aracaju 2016"
  date: "27 de agosto de 2016"
  price: "Gratuito!"
  address: "Av. Murilo Dantas, 300 - Farolândia"
  venue: "Universidade Tiradentes - Campus Farolândia"
  city: "Aracaju, Sergipe"

# Site info
site:
  author: "WTM Aracaju"
  url: "http://wtm.gdgaracaju.com.br"
  favicon: "http://wtm.gdgaracaju.com.br/img/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/og_image.png"
    facebook: "http://wtm.gdgaracaju.com.br/img/og_image.png"

subscribe_text: "Inscreva-se gratuitamente!"
subscribe_url: "http://go.gdg.link/f"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: false
  schedule: true
  sponsors: true
  partners: true
  contact: false
  tickets: false

# Organizers list
organizers:
  -
    name: "WTM Aracaju"
    photo: "./img/favicon.ico"
    url: "http://gdg.link/wtmaracaju/"
    bio: ""
    company: ""
  -
    name: "Jéssica Costa"
    photo: "./img/speakers/jessica_costa.jpg"
    url: "https://www.facebook.com/jessica.ufs"
    bio: "Desenvolvedora Web. Formada em Sistemas de Informação pela Universidade Federal de Sergipe. Desde de que entrou para o GDG Aracaju está trabalhando arduamente para promover o WTM em Aracaju."
    company: ""
  -
    name: "Ana Costa"
    photo: "./img/speakers/ana_costa.jpg"
    url: ""
    bio: ""
    company: ""
  -
    name: "Carla Almeida"
    photo: "./img/speakers/carla_almeida.jpg"
    url: ""
    bio: ""
    company: ""
  -
    name: "Danielle Ismerim"
    photo: "./img/speakers/danielle_ismerim.jpg"
    url: ""
    bio: ""
    company: ""
  -
    name: "Milene Vieira"
    photo: "./img/speakers/milene_vieira.jpg"
    url: ""
    bio: ""
    company: ""
  -
    name: "GDG Aracaju"
    photo: "./img/partners/gdgaracaju.png"
    url: "http://site.gdgaracaju.com.br/"
    bio: ""
    company: ""
  -
    name: "Erick Mendonça"
    photo: "./img/speakers/erick_mendonca.jpg"
    url: "http://github.com/erickmendonca"
    bio: "Formando na Universidade Federal de Sergipe e possui experiência como desenvolvedor e analista de sistemas. Co-organizador do Google Developer Group Aracaju, busca compartilhar conhecimento e aperfeiçoar a comunidade local de desenvolvedores e empreendedores através de eventos técnicos e encontros descontraídos para incentivar o crescimento e a empatia da comunidade local."
    company: "UFS"
  -
    name: "Italo Marcel"
    photo: "./img/speakers/italo_marcel.jpg"
    url: "https://github.com/italomarcel"
    bio: ""
    company: "Getinfo"
  -
    name: "Raphael Pantaleão"
    photo: "./img/speakers/raphael.jpg"
    url: "http://github.com/raphaelpanta"
    bio: ""
    company: ""
  -
    name: "Roberto Brandini"
    photo: "./img/speakers/roberto_brandini.jpg"
    url: "https://www.facebook.com/roberto.brandini"
    bio: ""
    company: ""

# Speakers list
speakers:
  - 
    name: ""
    url: ""
    photo: "./img/speakers/.jpg"
    title: ""
    details: ""

# Schedule
schedule:
  -
    day: "2708W"
    name: "27/08: Workshop"
    description: ""
    #url: ""
    agenda:
      -
        name: "Workshop PyLadies (Minicurso de Python)"
        time:
          start: "10:00"
          end: "15:00"
        description: "Professora do Curso Técnico Áreas de Programacao para Internet e Jogos Digitais - Universidade Tiradentes."
        extra:
          text: "A inscrição para este minicurso é realizada através do endereço: "
          url: "http://go.gdg.link/g"
        speaker:
          name: "Alexandra dos Santos Rodrigues"
          photo: "/img/speakers/alexandra_rodrigues.jpg"
          url: ""
  -
    day: "2708P"
    name: "27/08: Palestras"
    description: ""
    #url: ""
    agenda:
      -
        name: "Abertura"
        time:
          start: "09:30"
          end: "09:40"
        description: "Bacharel em Sistemas de Informação, Web Designer e GDG Organizer."
        speaker:
          name: "Jéssica da Silva Costa"
          photo: "/img/speakers/jessica_costa.jpg"
          url: ""
      -
        name: "Mulher - multitarefa e atuando em TI"
        time:
          start: "09:40"
          end: "10:30"
        description: "Bacharel em Ciência da Computação, Gerente de TI."
        speaker:
          name: "Cristina N Castro M Souza"
          photo: "/img/speakers/cristina_souza.jpg"
          url: ""
      -
        name: "Tendências na Área de TI"
        time:
          start: "10:30"
          end: "11:15"
        description: "Mestre em Ciência da Computação pela Universidade Federal de Sergipe (UFS). Possui MBA em Gerência de Projetos e graduação em Sistemas de Informação pela Unit. Atualmente é Gestora de Tecnologia da Informação e Comunicação (TIC) do Sergipe Parque Tecnológico e Diretora de Marketing e Eventos da Associação de Gestores de TI do Estado de Sergipe (CIO-SE)."
        speaker:
          name: "Carla Almeida"
          photo: "/img/speakers/carla_almeida.jpg"
          url: ""
      -
        name: "Criação de Sub-redes com IPV4"
        time:
          start: "11:15"
          end: "12:00"
        description: "Analista de Redes - Fase, graduanda em Sistemas de Informação - Fase, coordenadora de TI - Controladoria Geral do Estado."
        speaker:
          name: "Kelly Joany de Oliveira Santos"
          photo: "/img/speakers/kelly_oliveira.jpg"
          url: ""
      - 
        name: "Intervalo para almoço"
        time:
          start: "12:00"
          end: "13:00"
        description: ""
        speaker:
          name: ""
          photo: "/img/favicon.ico"
          url: ""
      -
        name: "Mulheres na indústria de games e quais oportunidades existem em Sergipe?"
        time:
          start: "13:00"
          end: "13:50"
        description: "Fabíola Monteiro: Designer (UNIT), Lead Artist na Lumentech. Daniel Caldas: Publicitário (UNIT), Head de Inteligência Estratégica na Zeca e criador do Laboratório 99."
        speaker:
          name: "Fabíola Monteiro e Daniel Caldas"
          photo: "/img/speakers/fabiola_monteiro.jpg"
          url: ""
      -
        name: "Propriedade Intelectual"
        time:
          start: "13:50"
          end: "14:40"
        description: "Graduada em Processamento de Dados - UNIT, Graduada em Licenciatura Plena, Formação Pedagógica para Formadores da Educação Profissional - UNISUL, Especialista em Didática do Ensino Superior - Faculdade Pio Décimo, Mestra em Modelagem Computacional de Conhecimento - UFAL, Professora do Instituto Federal de Sergipe (IFS), Coordenadora do Núcleo de Inovação Tecnológica do IFS"
        speaker:
          name: "Renata Tânia Brito Morais"
          photo: "/img/speakers/renata_morais.jpg"
          url: ""
      - 
        name: "Gestão de TIC: desafios e oportunidades da liderança feminina"
        time:
          start: "14:40"
          end: "15:30"
        description: "Professora Adjunto do Departamento de Computação da Universidade Federal de Sergipe (UFS) desde 2009. Doutora em Engenharia Elétrica (Sistemas Digitais) pela Escola Politécnica da Universidade de São Paulo. Mestre em Administração pela Pontifícia Universidade Católica de São Paulo. Especialista em Análise e Projeto de Sistemas pela FECAP. Graduada em Administração de Empresas pela Universidade Cruzeiro do Sul. Coordenou cursos de Sistemas de Informação e Ciência da Computação. Foi Gerente de Informática e Consultora na área de Tecnologia da Informação e Comunicação (TIC). Atua no Programa de Pós-Graduação em Ciência da Computação (PROCC/UFS). Gerencia o Setor de Gestão de Processos e Tecnologia da Informação do Hospital Universitário da UFS. Lidera o Grupo de Pesquisa em Informática em Saúde (GEPIS) e participa do Grupo de Pesquisa em Engenharia de Software do DCOMP/UFS. Tem interesse e desenvolve pesquisas que incluem: Engenharia de Software, Gestão de Projetos, Engenharia Web, Sistemas de Informação, Gestão de TIC, Gestão de Processos de Negócios e Informática em Saúde."
        speaker:
          name: "Adicinéia Oliveira"
          photo: "/img/speakers/adicineia_oliveira.jpg"
          url: ""
      - 
        name: "Coffee break"
        time:
          start: "15:30"
          end: "15:50"
        description: ""
        speaker:
          name: ""
          photo: "/img/favicon.ico"
          url: ""
      - 
        name: "Palestra surpresa"
        time:
          start: "15:50"
          end: "16:40"
        description: ""
        speaker:
          name: "GDG Aracaju"
          photo: "/img/gdg.png"
          url: ""
      - 
        name: "Encerramento"
        time:
          start: "16:40"
          end: "17:30"
        description: ""
        speaker:
          name: "GDG Aracaju"
          photo: "/img/gdg.png"
          url: ""


# List of Sponsors
sponsors:
  - 
    name: "Google Developers"
    logo: "./img/partners/google_developers.png"
    url: "http://developers.google.com/"
  - 
    name: "Women Techmakers"
    logo: "./img/partners/womentechmakers.jpeg"
    url: "http://womentechmakers.com/"
  - 
    name: "Universidade Tiradentes"
    logo: "./img/partners/unit.jpg"
    url: "http://unit.br/"
  - 
    name: "Escariz"
    logo: "./img/partners/escariz-logo.png"
    url: "http://www.escariz.com.br/"
  - 
    name: "CIO SE"
    logo: "./img/partners/ciose.jpg"
    url: "http://cio-se.org.br/"


# List of Partners
partners:
  -
    name: "CajuValley"
    logo: "./img/partners/cajuvalley.png"
    url: "https://www.facebook.com/cajuvalley"
  - 
    name: "SergipeTec"
    logo: "./img/partners/sergipetec.svg"
    url: "http://www.sergipetec.org.br/"


# About section
about_section:
   title: "Sobre"
   description: "O GDG Aracaju está bastante orgulhoso em trazer para Aracaju um programa de escala global Google para ajudar e empoderar mulheres. O WTM oferece visibilidade, comunidade e recursos para mulheres da tecnologia."

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: ""
   c4p_url: ""
   c4p_caption: "Preencha o form!"
   c4p_rules_url: ""
   c4p_rules_caption: ""

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

# Schedule section
schedule_section:
   title: "Programação"
   text: "A programação pode sofrer alterações sem avisos prévios."
   time: "Hora"
   slot: "Atividade"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"
